//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportPDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutiveReport
    {
        public int id { get; set; }
        public string area { get; set; }
        public string totalkomponen { get; set; }
        public string pembersihan1 { get; set; }
        public string pembersihan2 { get; set; }
        public string pembersihan3 { get; set; }
        public string perbaikan1 { get; set; }
        public string perbaikan2 { get; set; }
        public string perbaikan3 { get; set; }
        public string penggantian1 { get; set; }
        public string penggantian2 { get; set; }
        public string penggantian3 { get; set; }
    }
}
